plugins {
    id "com.android.application"
    id "kotlin-android"
}

android {
    namespace = "com.example.tarefas_domesticas"
    compileSdk = flutter.compileSdkVersion

    defaultConfig {
        applicationId = "com.example.tarefas_domesticas"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = 1
        versionName = "1.0"
    }
}

flutter {
    source = "../.."
}
